### ISSUE TITLE
Machine Learning 

### ISSUE THREAD

**Issue by eladmw** [NickBusey/SlitherBots#1]
Hi, I'm working on a slither.io bot right now, the main problem is with latency. On my computer I can only record at 45 fps (which might be good enough), and I need to use OCR to extract the length of the snake (128 ms per image).  I know that I could probably create more efficient schemas for extracting the length, but the most robust and efficient way seems to get it directly. As you have experience with Slither.io, it would be really helpful if you could explain how you would scrape it in real-time (and possibly save to an output file on my computer). I would be happy to push any ML code to your repo and to talk about the project.

**Comment by NickBusey** [comment]
I'm not using anything OCR related, I'm accessing the JavaScript game variables directly. You might try that approach.
